services:
  postgres:
    image: 'postgres:17.5-alpine'
    environment:
      - 'POSTGRES_DB=picto_db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=picto_user'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
