spring:
  application:
    name: Picto3

  datasource:
    url: jdbc:postgresql://${DATABASE_URL}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 40MB

  liquibase:
    change-log: classpath:/db/changelog/db-changelog-master.xml
    clear-checksums: true
    contexts: dev,prod,test

# For dev reasons
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

admin:
  game:
    api-key: ${ADMIN_KEY}
