package pl.umcs.picto3.game

enum class GameMessage(val type: String) {
    // Player events
    PLAYER_JOINED("PLAYER_JOINED"),
    PLAYER_WELCOME("PLAYER_WELCOME"),
    PLAYER_LEFT("PLAYER_LEFT"),

    SPEAKER_STAGE_1("SPEAKER_STAGE_1"),
    SPEAKER_STAGE_2("SPEAKER_STAGE_2"),

    LISTENER_STAGE_1("LISTENER_STAGE_1"),
    LISTENER_STAGE_2("LISTENER_STAGE_2"),

    // Admin events
    ADMIN_CONNECTED("ADMIN_CONNECTED"),

    GAME_STARTED("GAME_STARTED"),
    ERROR("ERROR"),
}